/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package alluxio.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)")
public class GetStatusTOptions implements org.apache.thrift.TBase<GetStatusTOptions, GetStatusTOptions._Fields>, java.io.Serializable, Cloneable, Comparable<GetStatusTOptions> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GetStatusTOptions");

  private static final org.apache.thrift.protocol.TField LOAD_METADATA_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("loadMetadataType", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField VARNAME_FIELD_DESC = new org.apache.thrift.protocol.TField("varname", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField QUERY_MAX_FIELD_DESC = new org.apache.thrift.protocol.TField("query_max", org.apache.thrift.protocol.TType.DOUBLE, (short)3);
  private static final org.apache.thrift.protocol.TField QUERY_MIN_FIELD_DESC = new org.apache.thrift.protocol.TField("query_min", org.apache.thrift.protocol.TType.DOUBLE, (short)4);
  private static final org.apache.thrift.protocol.TField IS_QUERY_FIELD_DESC = new org.apache.thrift.protocol.TField("isQuery", org.apache.thrift.protocol.TType.BOOL, (short)5);
  private static final org.apache.thrift.protocol.TField QUERY_AUGMENTED_FIELD_DESC = new org.apache.thrift.protocol.TField("query_augmented", org.apache.thrift.protocol.TType.BOOL, (short)6);
  private static final org.apache.thrift.protocol.TField ENABLE_PREFETCH_FIELD_DESC = new org.apache.thrift.protocol.TField("enablePrefetch", org.apache.thrift.protocol.TType.BOOL, (short)7);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new GetStatusTOptionsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new GetStatusTOptionsTupleSchemeFactory());
  }

  private LoadMetadataTType loadMetadataType; // optional
  private String varname; // optional
  private double query_max; // optional
  private double query_min; // optional
  private boolean isQuery; // optional
  private boolean query_augmented; // optional
  private boolean enablePrefetch; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see LoadMetadataTType
     */
    LOAD_METADATA_TYPE((short)1, "loadMetadataType"),
    VARNAME((short)2, "varname"),
    QUERY_MAX((short)3, "query_max"),
    QUERY_MIN((short)4, "query_min"),
    IS_QUERY((short)5, "isQuery"),
    QUERY_AUGMENTED((short)6, "query_augmented"),
    ENABLE_PREFETCH((short)7, "enablePrefetch");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LOAD_METADATA_TYPE
          return LOAD_METADATA_TYPE;
        case 2: // VARNAME
          return VARNAME;
        case 3: // QUERY_MAX
          return QUERY_MAX;
        case 4: // QUERY_MIN
          return QUERY_MIN;
        case 5: // IS_QUERY
          return IS_QUERY;
        case 6: // QUERY_AUGMENTED
          return QUERY_AUGMENTED;
        case 7: // ENABLE_PREFETCH
          return ENABLE_PREFETCH;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __QUERY_MAX_ISSET_ID = 0;
  private static final int __QUERY_MIN_ISSET_ID = 1;
  private static final int __ISQUERY_ISSET_ID = 2;
  private static final int __QUERY_AUGMENTED_ISSET_ID = 3;
  private static final int __ENABLEPREFETCH_ISSET_ID = 4;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.LOAD_METADATA_TYPE,_Fields.VARNAME,_Fields.QUERY_MAX,_Fields.QUERY_MIN,_Fields.IS_QUERY,_Fields.QUERY_AUGMENTED,_Fields.ENABLE_PREFETCH};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LOAD_METADATA_TYPE, new org.apache.thrift.meta_data.FieldMetaData("loadMetadataType", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, LoadMetadataTType.class)));
    tmpMap.put(_Fields.VARNAME, new org.apache.thrift.meta_data.FieldMetaData("varname", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.QUERY_MAX, new org.apache.thrift.meta_data.FieldMetaData("query_max", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.QUERY_MIN, new org.apache.thrift.meta_data.FieldMetaData("query_min", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.IS_QUERY, new org.apache.thrift.meta_data.FieldMetaData("isQuery", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.QUERY_AUGMENTED, new org.apache.thrift.meta_data.FieldMetaData("query_augmented", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.ENABLE_PREFETCH, new org.apache.thrift.meta_data.FieldMetaData("enablePrefetch", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GetStatusTOptions.class, metaDataMap);
  }

  public GetStatusTOptions() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public GetStatusTOptions(GetStatusTOptions other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetLoadMetadataType()) {
      this.loadMetadataType = other.loadMetadataType;
    }
    if (other.isSetVarname()) {
      this.varname = other.varname;
    }
    this.query_max = other.query_max;
    this.query_min = other.query_min;
    this.isQuery = other.isQuery;
    this.query_augmented = other.query_augmented;
    this.enablePrefetch = other.enablePrefetch;
  }

  public GetStatusTOptions deepCopy() {
    return new GetStatusTOptions(this);
  }

  @Override
  public void clear() {
    this.loadMetadataType = null;
    this.varname = null;
    setQuery_maxIsSet(false);
    this.query_max = 0.0;
    setQuery_minIsSet(false);
    this.query_min = 0.0;
    setIsQueryIsSet(false);
    this.isQuery = false;
    setQuery_augmentedIsSet(false);
    this.query_augmented = false;
    setEnablePrefetchIsSet(false);
    this.enablePrefetch = false;
  }

  /**
   * 
   * @see LoadMetadataTType
   */
  public LoadMetadataTType getLoadMetadataType() {
    return this.loadMetadataType;
  }

  /**
   * 
   * @see LoadMetadataTType
   */
  public GetStatusTOptions setLoadMetadataType(LoadMetadataTType loadMetadataType) {
    this.loadMetadataType = loadMetadataType;
    return this;
  }

  public void unsetLoadMetadataType() {
    this.loadMetadataType = null;
  }

  /** Returns true if field loadMetadataType is set (has been assigned a value) and false otherwise */
  public boolean isSetLoadMetadataType() {
    return this.loadMetadataType != null;
  }

  public void setLoadMetadataTypeIsSet(boolean value) {
    if (!value) {
      this.loadMetadataType = null;
    }
  }

  public String getVarname() {
    return this.varname;
  }

  public GetStatusTOptions setVarname(String varname) {
    this.varname = varname;
    return this;
  }

  public void unsetVarname() {
    this.varname = null;
  }

  /** Returns true if field varname is set (has been assigned a value) and false otherwise */
  public boolean isSetVarname() {
    return this.varname != null;
  }

  public void setVarnameIsSet(boolean value) {
    if (!value) {
      this.varname = null;
    }
  }

  public double getQuery_max() {
    return this.query_max;
  }

  public GetStatusTOptions setQuery_max(double query_max) {
    this.query_max = query_max;
    setQuery_maxIsSet(true);
    return this;
  }

  public void unsetQuery_max() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __QUERY_MAX_ISSET_ID);
  }

  /** Returns true if field query_max is set (has been assigned a value) and false otherwise */
  public boolean isSetQuery_max() {
    return EncodingUtils.testBit(__isset_bitfield, __QUERY_MAX_ISSET_ID);
  }

  public void setQuery_maxIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __QUERY_MAX_ISSET_ID, value);
  }

  public double getQuery_min() {
    return this.query_min;
  }

  public GetStatusTOptions setQuery_min(double query_min) {
    this.query_min = query_min;
    setQuery_minIsSet(true);
    return this;
  }

  public void unsetQuery_min() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __QUERY_MIN_ISSET_ID);
  }

  /** Returns true if field query_min is set (has been assigned a value) and false otherwise */
  public boolean isSetQuery_min() {
    return EncodingUtils.testBit(__isset_bitfield, __QUERY_MIN_ISSET_ID);
  }

  public void setQuery_minIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __QUERY_MIN_ISSET_ID, value);
  }

  public boolean isIsQuery() {
    return this.isQuery;
  }

  public GetStatusTOptions setIsQuery(boolean isQuery) {
    this.isQuery = isQuery;
    setIsQueryIsSet(true);
    return this;
  }

  public void unsetIsQuery() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ISQUERY_ISSET_ID);
  }

  /** Returns true if field isQuery is set (has been assigned a value) and false otherwise */
  public boolean isSetIsQuery() {
    return EncodingUtils.testBit(__isset_bitfield, __ISQUERY_ISSET_ID);
  }

  public void setIsQueryIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ISQUERY_ISSET_ID, value);
  }

  public boolean isQuery_augmented() {
    return this.query_augmented;
  }

  public GetStatusTOptions setQuery_augmented(boolean query_augmented) {
    this.query_augmented = query_augmented;
    setQuery_augmentedIsSet(true);
    return this;
  }

  public void unsetQuery_augmented() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __QUERY_AUGMENTED_ISSET_ID);
  }

  /** Returns true if field query_augmented is set (has been assigned a value) and false otherwise */
  public boolean isSetQuery_augmented() {
    return EncodingUtils.testBit(__isset_bitfield, __QUERY_AUGMENTED_ISSET_ID);
  }

  public void setQuery_augmentedIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __QUERY_AUGMENTED_ISSET_ID, value);
  }

  public boolean isEnablePrefetch() {
    return this.enablePrefetch;
  }

  public GetStatusTOptions setEnablePrefetch(boolean enablePrefetch) {
    this.enablePrefetch = enablePrefetch;
    setEnablePrefetchIsSet(true);
    return this;
  }

  public void unsetEnablePrefetch() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ENABLEPREFETCH_ISSET_ID);
  }

  /** Returns true if field enablePrefetch is set (has been assigned a value) and false otherwise */
  public boolean isSetEnablePrefetch() {
    return EncodingUtils.testBit(__isset_bitfield, __ENABLEPREFETCH_ISSET_ID);
  }

  public void setEnablePrefetchIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ENABLEPREFETCH_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case LOAD_METADATA_TYPE:
      if (value == null) {
        unsetLoadMetadataType();
      } else {
        setLoadMetadataType((LoadMetadataTType)value);
      }
      break;

    case VARNAME:
      if (value == null) {
        unsetVarname();
      } else {
        setVarname((String)value);
      }
      break;

    case QUERY_MAX:
      if (value == null) {
        unsetQuery_max();
      } else {
        setQuery_max((Double)value);
      }
      break;

    case QUERY_MIN:
      if (value == null) {
        unsetQuery_min();
      } else {
        setQuery_min((Double)value);
      }
      break;

    case IS_QUERY:
      if (value == null) {
        unsetIsQuery();
      } else {
        setIsQuery((Boolean)value);
      }
      break;

    case QUERY_AUGMENTED:
      if (value == null) {
        unsetQuery_augmented();
      } else {
        setQuery_augmented((Boolean)value);
      }
      break;

    case ENABLE_PREFETCH:
      if (value == null) {
        unsetEnablePrefetch();
      } else {
        setEnablePrefetch((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case LOAD_METADATA_TYPE:
      return getLoadMetadataType();

    case VARNAME:
      return getVarname();

    case QUERY_MAX:
      return getQuery_max();

    case QUERY_MIN:
      return getQuery_min();

    case IS_QUERY:
      return isIsQuery();

    case QUERY_AUGMENTED:
      return isQuery_augmented();

    case ENABLE_PREFETCH:
      return isEnablePrefetch();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case LOAD_METADATA_TYPE:
      return isSetLoadMetadataType();
    case VARNAME:
      return isSetVarname();
    case QUERY_MAX:
      return isSetQuery_max();
    case QUERY_MIN:
      return isSetQuery_min();
    case IS_QUERY:
      return isSetIsQuery();
    case QUERY_AUGMENTED:
      return isSetQuery_augmented();
    case ENABLE_PREFETCH:
      return isSetEnablePrefetch();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof GetStatusTOptions)
      return this.equals((GetStatusTOptions)that);
    return false;
  }

  public boolean equals(GetStatusTOptions that) {
    if (that == null)
      return false;

    boolean this_present_loadMetadataType = true && this.isSetLoadMetadataType();
    boolean that_present_loadMetadataType = true && that.isSetLoadMetadataType();
    if (this_present_loadMetadataType || that_present_loadMetadataType) {
      if (!(this_present_loadMetadataType && that_present_loadMetadataType))
        return false;
      if (!this.loadMetadataType.equals(that.loadMetadataType))
        return false;
    }

    boolean this_present_varname = true && this.isSetVarname();
    boolean that_present_varname = true && that.isSetVarname();
    if (this_present_varname || that_present_varname) {
      if (!(this_present_varname && that_present_varname))
        return false;
      if (!this.varname.equals(that.varname))
        return false;
    }

    boolean this_present_query_max = true && this.isSetQuery_max();
    boolean that_present_query_max = true && that.isSetQuery_max();
    if (this_present_query_max || that_present_query_max) {
      if (!(this_present_query_max && that_present_query_max))
        return false;
      if (this.query_max != that.query_max)
        return false;
    }

    boolean this_present_query_min = true && this.isSetQuery_min();
    boolean that_present_query_min = true && that.isSetQuery_min();
    if (this_present_query_min || that_present_query_min) {
      if (!(this_present_query_min && that_present_query_min))
        return false;
      if (this.query_min != that.query_min)
        return false;
    }

    boolean this_present_isQuery = true && this.isSetIsQuery();
    boolean that_present_isQuery = true && that.isSetIsQuery();
    if (this_present_isQuery || that_present_isQuery) {
      if (!(this_present_isQuery && that_present_isQuery))
        return false;
      if (this.isQuery != that.isQuery)
        return false;
    }

    boolean this_present_query_augmented = true && this.isSetQuery_augmented();
    boolean that_present_query_augmented = true && that.isSetQuery_augmented();
    if (this_present_query_augmented || that_present_query_augmented) {
      if (!(this_present_query_augmented && that_present_query_augmented))
        return false;
      if (this.query_augmented != that.query_augmented)
        return false;
    }

    boolean this_present_enablePrefetch = true && this.isSetEnablePrefetch();
    boolean that_present_enablePrefetch = true && that.isSetEnablePrefetch();
    if (this_present_enablePrefetch || that_present_enablePrefetch) {
      if (!(this_present_enablePrefetch && that_present_enablePrefetch))
        return false;
      if (this.enablePrefetch != that.enablePrefetch)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_loadMetadataType = true && (isSetLoadMetadataType());
    list.add(present_loadMetadataType);
    if (present_loadMetadataType)
      list.add(loadMetadataType.getValue());

    boolean present_varname = true && (isSetVarname());
    list.add(present_varname);
    if (present_varname)
      list.add(varname);

    boolean present_query_max = true && (isSetQuery_max());
    list.add(present_query_max);
    if (present_query_max)
      list.add(query_max);

    boolean present_query_min = true && (isSetQuery_min());
    list.add(present_query_min);
    if (present_query_min)
      list.add(query_min);

    boolean present_isQuery = true && (isSetIsQuery());
    list.add(present_isQuery);
    if (present_isQuery)
      list.add(isQuery);

    boolean present_query_augmented = true && (isSetQuery_augmented());
    list.add(present_query_augmented);
    if (present_query_augmented)
      list.add(query_augmented);

    boolean present_enablePrefetch = true && (isSetEnablePrefetch());
    list.add(present_enablePrefetch);
    if (present_enablePrefetch)
      list.add(enablePrefetch);

    return list.hashCode();
  }

  @Override
  public int compareTo(GetStatusTOptions other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetLoadMetadataType()).compareTo(other.isSetLoadMetadataType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLoadMetadataType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.loadMetadataType, other.loadMetadataType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetVarname()).compareTo(other.isSetVarname());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVarname()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.varname, other.varname);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQuery_max()).compareTo(other.isSetQuery_max());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQuery_max()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.query_max, other.query_max);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQuery_min()).compareTo(other.isSetQuery_min());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQuery_min()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.query_min, other.query_min);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIsQuery()).compareTo(other.isSetIsQuery());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsQuery()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isQuery, other.isQuery);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQuery_augmented()).compareTo(other.isSetQuery_augmented());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQuery_augmented()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.query_augmented, other.query_augmented);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEnablePrefetch()).compareTo(other.isSetEnablePrefetch());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEnablePrefetch()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.enablePrefetch, other.enablePrefetch);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("GetStatusTOptions(");
    boolean first = true;

    if (isSetLoadMetadataType()) {
      sb.append("loadMetadataType:");
      if (this.loadMetadataType == null) {
        sb.append("null");
      } else {
        sb.append(this.loadMetadataType);
      }
      first = false;
    }
    if (isSetVarname()) {
      if (!first) sb.append(", ");
      sb.append("varname:");
      if (this.varname == null) {
        sb.append("null");
      } else {
        sb.append(this.varname);
      }
      first = false;
    }
    if (isSetQuery_max()) {
      if (!first) sb.append(", ");
      sb.append("query_max:");
      sb.append(this.query_max);
      first = false;
    }
    if (isSetQuery_min()) {
      if (!first) sb.append(", ");
      sb.append("query_min:");
      sb.append(this.query_min);
      first = false;
    }
    if (isSetIsQuery()) {
      if (!first) sb.append(", ");
      sb.append("isQuery:");
      sb.append(this.isQuery);
      first = false;
    }
    if (isSetQuery_augmented()) {
      if (!first) sb.append(", ");
      sb.append("query_augmented:");
      sb.append(this.query_augmented);
      first = false;
    }
    if (isSetEnablePrefetch()) {
      if (!first) sb.append(", ");
      sb.append("enablePrefetch:");
      sb.append(this.enablePrefetch);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GetStatusTOptionsStandardSchemeFactory implements SchemeFactory {
    public GetStatusTOptionsStandardScheme getScheme() {
      return new GetStatusTOptionsStandardScheme();
    }
  }

  private static class GetStatusTOptionsStandardScheme extends StandardScheme<GetStatusTOptions> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, GetStatusTOptions struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LOAD_METADATA_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.loadMetadataType = alluxio.thrift.LoadMetadataTType.findByValue(iprot.readI32());
              struct.setLoadMetadataTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // VARNAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.varname = iprot.readString();
              struct.setVarnameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // QUERY_MAX
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.query_max = iprot.readDouble();
              struct.setQuery_maxIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // QUERY_MIN
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.query_min = iprot.readDouble();
              struct.setQuery_minIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // IS_QUERY
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isQuery = iprot.readBool();
              struct.setIsQueryIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // QUERY_AUGMENTED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.query_augmented = iprot.readBool();
              struct.setQuery_augmentedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // ENABLE_PREFETCH
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.enablePrefetch = iprot.readBool();
              struct.setEnablePrefetchIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, GetStatusTOptions struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.loadMetadataType != null) {
        if (struct.isSetLoadMetadataType()) {
          oprot.writeFieldBegin(LOAD_METADATA_TYPE_FIELD_DESC);
          oprot.writeI32(struct.loadMetadataType.getValue());
          oprot.writeFieldEnd();
        }
      }
      if (struct.varname != null) {
        if (struct.isSetVarname()) {
          oprot.writeFieldBegin(VARNAME_FIELD_DESC);
          oprot.writeString(struct.varname);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetQuery_max()) {
        oprot.writeFieldBegin(QUERY_MAX_FIELD_DESC);
        oprot.writeDouble(struct.query_max);
        oprot.writeFieldEnd();
      }
      if (struct.isSetQuery_min()) {
        oprot.writeFieldBegin(QUERY_MIN_FIELD_DESC);
        oprot.writeDouble(struct.query_min);
        oprot.writeFieldEnd();
      }
      if (struct.isSetIsQuery()) {
        oprot.writeFieldBegin(IS_QUERY_FIELD_DESC);
        oprot.writeBool(struct.isQuery);
        oprot.writeFieldEnd();
      }
      if (struct.isSetQuery_augmented()) {
        oprot.writeFieldBegin(QUERY_AUGMENTED_FIELD_DESC);
        oprot.writeBool(struct.query_augmented);
        oprot.writeFieldEnd();
      }
      if (struct.isSetEnablePrefetch()) {
        oprot.writeFieldBegin(ENABLE_PREFETCH_FIELD_DESC);
        oprot.writeBool(struct.enablePrefetch);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GetStatusTOptionsTupleSchemeFactory implements SchemeFactory {
    public GetStatusTOptionsTupleScheme getScheme() {
      return new GetStatusTOptionsTupleScheme();
    }
  }

  private static class GetStatusTOptionsTupleScheme extends TupleScheme<GetStatusTOptions> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, GetStatusTOptions struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetLoadMetadataType()) {
        optionals.set(0);
      }
      if (struct.isSetVarname()) {
        optionals.set(1);
      }
      if (struct.isSetQuery_max()) {
        optionals.set(2);
      }
      if (struct.isSetQuery_min()) {
        optionals.set(3);
      }
      if (struct.isSetIsQuery()) {
        optionals.set(4);
      }
      if (struct.isSetQuery_augmented()) {
        optionals.set(5);
      }
      if (struct.isSetEnablePrefetch()) {
        optionals.set(6);
      }
      oprot.writeBitSet(optionals, 7);
      if (struct.isSetLoadMetadataType()) {
        oprot.writeI32(struct.loadMetadataType.getValue());
      }
      if (struct.isSetVarname()) {
        oprot.writeString(struct.varname);
      }
      if (struct.isSetQuery_max()) {
        oprot.writeDouble(struct.query_max);
      }
      if (struct.isSetQuery_min()) {
        oprot.writeDouble(struct.query_min);
      }
      if (struct.isSetIsQuery()) {
        oprot.writeBool(struct.isQuery);
      }
      if (struct.isSetQuery_augmented()) {
        oprot.writeBool(struct.query_augmented);
      }
      if (struct.isSetEnablePrefetch()) {
        oprot.writeBool(struct.enablePrefetch);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, GetStatusTOptions struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(7);
      if (incoming.get(0)) {
        struct.loadMetadataType = alluxio.thrift.LoadMetadataTType.findByValue(iprot.readI32());
        struct.setLoadMetadataTypeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.varname = iprot.readString();
        struct.setVarnameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.query_max = iprot.readDouble();
        struct.setQuery_maxIsSet(true);
      }
      if (incoming.get(3)) {
        struct.query_min = iprot.readDouble();
        struct.setQuery_minIsSet(true);
      }
      if (incoming.get(4)) {
        struct.isQuery = iprot.readBool();
        struct.setIsQueryIsSet(true);
      }
      if (incoming.get(5)) {
        struct.query_augmented = iprot.readBool();
        struct.setQuery_augmentedIsSet(true);
      }
      if (incoming.get(6)) {
        struct.enablePrefetch = iprot.readBool();
        struct.setEnablePrefetchIsSet(true);
      }
    }
  }

}

